# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'pagatodoChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for pagatodoChallenge
  pod 'SDWebImageSwiftUI'
  plugin 'cocoapods-keys', {
  :project => "pagatodoChallenge",
  :keys => [
    "PagatodoURL",
  ]} 
 target 'pagatodoChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
